"""
02b_generate_bg_videos.py — Animate background images into short videos using WAN 2.2 i2v
===========================================================================================
PURPOSE:
  Takes a static background PNG (already generated by 02_generate_backgrounds.py)
  and sends it to ComfyUI's WAN 2.2 image-to-video model to generate ~5 seconds
  of gentle ambient motion.

  The output MP4 is saved alongside the PNG with the same base name:
    output/backgrounds/sax_signature_1x1.mp4

  When 03_populate_templates.py runs after this, it automatically prefers the .mp4
  over the .png when both exist — so the AE render uses the animated background.

HOW IT WORKS:
  1. Finds the existing background PNG for the target product+ratio
  2. Uploads it to ComfyUI via the /upload/image API
  3. Builds a WAN 2.2 i2v workflow with:
       - The uploaded image as the starting frame
       - A motion prompt (scene description + ambient motion descriptors)
       - 640x640 output (upscaled to 1080x1080 by AE — saves VRAM and generation time)
       - 81 frames at 16fps = ~5 seconds
  4. Polls ComfyUI until the video is ready
  5. Copies the output MP4 from G:/ComfyUI/output/ to output/backgrounds/

RUN:
  python scripts/02b_generate_bg_videos.py                    # sax_signature 1x1 (default)
  python scripts/02b_generate_bg_videos.py --product sax_signature --ratio 1x1
"""

import argparse
import copy
import json
import shutil
import sys
import time
import uuid
from pathlib import Path

sys.path.insert(0, str(Path(__file__).parent.parent))
import os
os.environ["PYTHONIOENCODING"] = "utf-8"

import requests

from config import BACKGROUNDS_DIR, COMFYUI_URL, COMFYUI_WORKFLOWS_DIR, VARIANTS_JSON
from scripts.utils.logger import log


# ─────────────────────────────────────────────
# COMFYUI OUTPUT FOLDER
# Same as 02_generate_backgrounds.py
# ─────────────────────────────────────────────
COMFYUI_OUTPUT_DIR = Path("G:/ComfyUI/output")

# ─────────────────────────────────────────────
# VIDEO DIMENSIONS PER RATIO
# Lower than the PNG dimensions to keep VRAM usage manageable.
# AE scales the video up to fill the composition — quality is fine for backgrounds.
# ─────────────────────────────────────────────
VIDEO_DIMENSIONS = {
    "1x1":               (640, 640),   # AE comp is 1080x1080, generates at 640x640
    "16x9":              (832, 480),   # AE comp is 1920x1080, generates at 832x480
    "billboard_970x250": (832, 208),   # AE comp is 970x250 (3x = 2910x750), generates at 832x208
}

# ─────────────────────────────────────────────
# MOTION PROMPT SUFFIX
# Added to the original scene description to tell WAN how to move the scene.
# Keep it subtle — this is a background, not the hero.
# ─────────────────────────────────────────────
# For i2v, the image provides the visual content — the prompt should describe
# MOTION ONLY, not re-describe the scene. Describing the scene causes the model
# to hallucinate new content instead of just animating the existing image.
MOTION_PROMPT = (
    "gentle atmospheric motion, slow bokeh drift, subtle light pulse, "
    "soft ambient particle float, no camera movement, same scene, same environment"
)

# ─────────────────────────────────────────────
# LTX2 i2v WORKFLOW NODE IDs
# These match video_ltx2_i2v.json exactly.
# ─────────────────────────────────────────────
NODE = {
    "load_image":      "98",     # LoadImage — image field = uploaded filename
    "positive_prompt": "92:3",   # CLIPTextEncode — text field = motion prompt
    "seed_main":       "92:11",  # RandomNoise (first pass) — noise_seed field
    "seed_refine":     "92:67",  # RandomNoise (refinement pass) — noise_seed field
    "save_video":      "75",     # SaveVideo — filename_prefix field
    "frames":          "92:62",  # PrimitiveInt — frame count (LTX2 requires 8n+1)
}

# ─────────────────────────────────────────────
# VIDEO LENGTH
# LTX2 requires frame count to follow the formula: 8n + 1
# Examples: 121 = ~4.8s, 169 = ~6.8s, 249 = ~10s at 25fps
# ─────────────────────────────────────────────
VIDEO_FRAMES = 249   # 8×31+1 = 249 frames @ 25fps = ~10 seconds

# How long to poll for (video takes longer than images)
POLL_INTERVAL = 5   # seconds between status checks
MAX_WAIT      = 3600 # 60 minutes max (WAN 2.2 14B at 81 frames takes ~10-20 min)


def load_workflow() -> dict:
    path = COMFYUI_WORKFLOWS_DIR / "video_ltx2_i2v.json"
    if not path.exists():
        log.error(f"Workflow not found: {path}")
        sys.exit(1)
    with open(path, encoding="utf-8") as f:
        return json.load(f)


def upload_image(image_path: Path) -> str:
    """
    Uploads a PNG to ComfyUI's input folder via the API.
    Returns the filename ComfyUI assigned (used in the LoadImage node).

    Why we upload instead of using a file path directly:
      ComfyUI's LoadImage node only looks in its own input/ folder.
      The upload API moves our file there and returns the safe filename.
    """
    log.info(f"  Uploading image to ComfyUI: {image_path.name}")
    with open(image_path, "rb") as f:
        resp = requests.post(
            f"{COMFYUI_URL}/upload/image",
            files={"image": (image_path.name, f, "image/png")},
            data={"type": "input", "overwrite": "true"},
            timeout=30,
        )
    resp.raise_for_status()
    uploaded_name = resp.json()["name"]
    log.info(f"  Uploaded as: {uploaded_name}")
    return uploaded_name


def build_workflow(base_workflow: dict, uploaded_image: str, prompt: str,
                   width: int, height: int, prefix: str) -> dict:
    """
    Returns a modified copy of the LTX2 i2v workflow with our values injected.

    Changes made:
      - Node 98  (LoadImage): image → our uploaded background PNG
      - Node 92:3 (CLIPTextEncode): text → motion-only prompt
      - Node 92:11 (RandomNoise): seed → randomised
      - Node 92:67 (RandomNoise): seed → randomised (refinement pass)
      - Node 75  (SaveVideo): filename_prefix → unique prefix so we can find the output

    Note: width/height are handled automatically by the workflow's ResizeImageMaskNode
    (node 102) which reads the image dimensions, so we don't need to inject them.
    prompt (scene description) is intentionally unused — the image provides the scene.
    """
    _ = prompt  # not used — image conditioning provides the scene
    wf = copy.deepcopy(base_workflow)

    # Set the input image
    wf[NODE["load_image"]]["inputs"]["image"] = uploaded_image

    # Motion-only prompt — the image provides the scene content
    wf[NODE["positive_prompt"]]["inputs"]["text"] = MOTION_PROMPT

    # Randomise both noise seeds so each generation is unique
    seed = int(uuid.uuid4().int % (2**32))
    wf[NODE["seed_main"]]["inputs"]["noise_seed"]   = seed
    wf[NODE["seed_refine"]]["inputs"]["noise_seed"] = seed + 1

    # Unique prefix so we can find THIS job's output video in G:/ComfyUI/output/
    wf[NODE["save_video"]]["inputs"]["filename_prefix"] = prefix

    # Frame count — 249 frames at 25fps = ~10 seconds
    # LTX2 requires 8n+1 frames (e.g. 121, 169, 249)
    wf[NODE["frames"]]["inputs"]["value"] = VIDEO_FRAMES

    return wf


def submit_job(workflow: dict) -> str:
    """Posts the workflow to ComfyUI and returns the prompt_id."""
    resp = requests.post(
        f"{COMFYUI_URL}/prompt",
        json={"prompt": workflow},
        timeout=30,
    )
    if not resp.ok:
        log.error(f"ComfyUI rejected the workflow (HTTP {resp.status_code}):")
        log.error(resp.text[:1000])
        sys.exit(1)
    return resp.json()["prompt_id"]


def wait_for_job(prompt_id: str) -> bool:
    """
    Polls ComfyUI until the job is done.
    Returns True if completed successfully, False if timed out or errored.

    Video generation takes much longer than images — hence the higher MAX_WAIT.
    """
    log.info(f"  Waiting for ComfyUI job {prompt_id[:8]}...")
    elapsed = 0
    while elapsed < MAX_WAIT:
        resp = requests.get(f"{COMFYUI_URL}/history/{prompt_id}", timeout=10)
        resp.raise_for_status()
        history = resp.json()

        if prompt_id in history:
            job = history[prompt_id]
            status = job.get("status", {})

            if status.get("status_str") == "success":
                return True
            if status.get("status_str") == "error":
                messages = status.get("messages", [])
                log.error(f"  ComfyUI job failed: {messages}")
                return False

        time.sleep(POLL_INTERVAL)
        elapsed += POLL_INTERVAL

        # Show progress every 30 seconds
        if elapsed % 30 == 0:
            log.info(f"  Still generating... ({elapsed}s elapsed)")

    log.error(f"  Timed out after {MAX_WAIT}s")
    return False


def find_output_video(prefix: str) -> Path | None:
    """
    Searches ComfyUI's output folder for the generated video file.
    SaveVideo saves as: {prefix}_00001.mp4 or {prefix}.mp4 — search recursively.
    """
    # SaveVideo may save into subfolders if prefix contains "/"
    matches = list(COMFYUI_OUTPUT_DIR.rglob(f"{prefix}*.mp4"))
    if not matches:
        return None
    return sorted(matches, key=lambda p: p.stat().st_mtime)[-1]


def free_comfyui_memory():
    """
    Tells ComfyUI to unload all models and free VRAM before we start.
    This is important when running after a Flux/ControlNet job — those models
    stay in VRAM and prevent LTX2 from loading. The /free endpoint forces
    ComfyUI to clear everything out first.
    """
    try:
        resp = requests.post(
            f"{COMFYUI_URL}/free",
            json={"unload_models": True, "free_memory": True},
            timeout=30,
        )
        if resp.ok:
            log.info("  Freed ComfyUI VRAM (unloaded previous models)")
        else:
            log.warn(f"  /free returned {resp.status_code} — continuing anyway")
    except Exception as e:
        log.warn(f"  Could not free VRAM: {e} — continuing anyway")
    # Give ComfyUI a moment to finish unloading
    time.sleep(3)


def run(product_id: str, ratio: str, source_override: str = None, force: bool = False):
    log.section(f"STEP 2b — GENERATE VIDEO BACKGROUND ({product_id} {ratio})")

    # ── Free VRAM from any previous ComfyUI jobs ───────────────────
    # Flux/ControlNet models from step 2a stay in VRAM and block LTX2.
    # Calling /free forces ComfyUI to unload them before we start.
    free_comfyui_memory()

    # ── Check dimensions are supported ─────────────────────────────
    if ratio not in VIDEO_DIMENSIONS:
        log.error(f"Unsupported ratio: {ratio}. Supported: {list(VIDEO_DIMENSIONS.keys())}")
        sys.exit(1)

    width, height = VIDEO_DIMENSIONS[ratio]

    # ── Find the source PNG ─────────────────────────────────────────
    # --source lets you point to a Cinema 4D render (Option C) instead of
    # the ComfyUI-generated background in the backgrounds folder.
    if source_override:
        source_png = Path(source_override)
        if not source_png.exists():
            log.error(f"Source image not found: {source_png}")
            sys.exit(1)
        log.info(f"  Using custom source image: {source_png}")
    else:
        source_png = BACKGROUNDS_DIR / f"{product_id}_{ratio}.png"
        if not source_png.exists():
            log.error(f"Source background PNG not found: {source_png}")
            log.error("Run 02_generate_backgrounds.py first to generate the PNG.")
            sys.exit(1)

    # ── Check output doesn't already exist ─────────────────────────
    output_mp4 = BACKGROUNDS_DIR / f"{product_id}_{ratio}.mp4"
    if output_mp4.exists():
        if force:
            log.warn(f"  --force set: overwriting existing video: {output_mp4.name}")
            output_mp4.unlink()
        else:
            log.ok(f"Video already exists — skipping: {output_mp4.name}")
            log.info("Use --force to overwrite, or delete the file and re-run.")
            return

    # ── Find the comfyui_prompt for this product from variants.json ─
    prompt = ""
    if VARIANTS_JSON.exists():
        with open(VARIANTS_JSON, encoding="utf-8") as f:
            variants = json.load(f)
        # Find a variant with this product + ratio to get the scene prompt
        match = next(
            (v for v in variants
             if v["product_id"] == product_id and v["ratio"] == ratio),
            None
        )
        if match:
            prompt = match.get("comfyui_prompt", "")

    if not prompt:
        # Fallback if no prompt found
        prompt = "cinematic background scene, atmospheric lighting, depth of field"
        log.warn(f"  No comfyui_prompt found for {product_id}/{ratio} — using fallback prompt")
    else:
        log.info(f"  Using prompt: {prompt[:80]}...")

    # ── Check ComfyUI is running ────────────────────────────────────
    try:
        requests.get(f"{COMFYUI_URL}/system_stats", timeout=5)
    except requests.ConnectionError:
        log.error(f"Cannot reach ComfyUI at {COMFYUI_URL}")
        log.error("Make sure ComfyUI is running before running this script.")
        sys.exit(1)

    # ── Upload the source image to ComfyUI ─────────────────────────
    uploaded_name = upload_image(source_png)

    # ── Build and submit the workflow ───────────────────────────────
    base_workflow = load_workflow()
    prefix = f"yosuki_bgvid_{product_id}_{ratio}"
    workflow = build_workflow(base_workflow, uploaded_name, prompt, width, height, prefix)

    log.info(f"  Submitting WAN 2.2 i2v job ({width}x{height}, {VIDEO_FRAMES} frames @ 25fps = ~10s)...")
    prompt_id = submit_job(workflow)

    # ── Wait for completion ─────────────────────────────────────────
    success = wait_for_job(prompt_id)
    if not success:
        log.error("Job failed — check ComfyUI for details.")
        sys.exit(1)

    # ── Find the output video ───────────────────────────────────────
    log.info("  Job complete. Searching for output video...")
    time.sleep(2)  # Brief pause to let ComfyUI finish writing the file
    video_path = find_output_video(prefix)

    if not video_path:
        log.error(f"Could not find output video with prefix '{prefix}' in {COMFYUI_OUTPUT_DIR}")
        log.error("Check G:/ComfyUI/output/ manually for the generated file.")
        sys.exit(1)

    # ── Copy to our backgrounds folder ─────────────────────────────
    shutil.copy2(video_path, output_mp4)
    size_mb = output_mp4.stat().st_size / (1024 * 1024)
    log.ok(f"  Saved: {output_mp4.name} ({size_mb:.1f} MB)")

    log.ok(f"Done! Video background ready at: output/backgrounds/{output_mp4.name}")
    log.info("Next step: python scripts/03_populate_templates.py --variant sax_signature_US_1x1")
    log.info("(The render script will automatically use the .mp4 over the .png)")


if __name__ == "__main__":
    parser = argparse.ArgumentParser(
        description="Animate a background PNG into a video using WAN 2.2 i2v."
    )
    parser.add_argument(
        "--product", type=str, default="sax_signature",
        help="Product ID (e.g. sax_signature). Default: sax_signature"
    )
    parser.add_argument(
        "--ratio", type=str, default="1x1",
        help="Aspect ratio (1x1, 16x9, billboard_970x250). Default: 1x1"
    )
    parser.add_argument(
        "--source", type=str, default=None,
        help="Optional: path to a custom source image (e.g. a Cinema 4D render). "
             "If not set, looks for the PNG in output/backgrounds/."
    )
    parser.add_argument(
        "--force", action="store_true", default=False,
        help="Overwrite the output video if it already exists."
    )
    args = parser.parse_args()
    run(product_id=args.product, ratio=args.ratio,
        source_override=args.source, force=args.force)
